rbot.local.accounts[0].email=admin@rbot.localhost
rbot.local.accounts[0].password=local-admin-password
rbot.local.accounts[0].roles=ADMIN,PSYCHOLOGIST
rbot.local.accounts[1].email=psychologist@rbot.localhost
rbot.local.accounts[1].password=local-psychologist-password
rbot.local.accounts[1].roles=PSYCHOLOGIST
