rbot.qa.accounts[0].email=admin@yanapaderina.test
rbot.qa.accounts[0].password=qa-admin-password
rbot.qa.accounts[0].roles=ADMIN,PSYCHOLOGIST
rbot.qa.accounts[1].email=psychologist@yanapaderina.test
rbot.qa.accounts[1].password=qa-psychologist-password
rbot.qa.accounts[1].roles=PSYCHOLOGIST
